#博客名称 #站点名，站点左上角
title: pitmates' blog 
#副标题 #副标题，站点左上角
subtitle: remember something 
#简介 #给搜索引擎看的，对站点的描述，可以自定义
description: record my lifestyle
#博客作者 #在站点左下角可以看到
author: pitmates
#email
#email:huicpc0807@163.com
#博客语言
language: zh-CN
#时区
timezone:

#博客地址,与申请的GitHub一致
# URL #这项暂不配置，绑定域名后，欲创建sitemap.xml需要配置该项
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://zlper.net
root: /
#博客链接格式
permalink: :year/:month/:day/:title/
permalink_defaults:

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render: README.md

# Writing 文章布局、写作格式的定义，不修改
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:

  # Category & Tag
default_category: uncategorized
category_map:
tag_map:

#*******************
# Archives 默认值为2，这里都修改为1，相应页面就只会列出标题，而非全文
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 1
tag: 1

# Server 不修改
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
logger: false
logger_format:

# Disqus Disqus插件，
#disqus_shortname: pitm

#Duoshuo 插件
duoshuo_shortname: pitm

#*************************

#日期格式
date_format: YYYY-MM-DD
time_format: HH:mm:ss

#分页，每页文章数量
per_page: 10
pagination_dir: page

#博客主题
# Extensions 这里配置站点所用主题和插件，暂默认，后面会介绍怎么修改
## Plugins: https://github.com/tommy351/hexo/wiki/Plugins
## Themes: https://github.com/tommy351/hexo/wiki/Themes
theme: hexa
exclude_generator:
plugins:
#- hexo-generator-feed
#- hexo-generator-sitemap


#发布设置
deploy: 
  type: git
  #pitmates 改为你的github用户名
  repository: https://github.com/pitmates/pitmates.github.io.git
  branch: master

mathjax: true
